name: Deploy to EC2

on:
  push:
    branches:
      - master # or main, depending on your branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Add SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}
        ssh-passphrase: ${{ secrets.EC2_SSH_PASSPHRASE }}

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ec2-user@your-ec2-ip << 'EOF'
          cd /path/to/your/app
          git pull origin master  # or main
          docker-compose down     # if using Docker Compose
          docker-compose up -d    # if using Docker Compose
        EOF
