name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run SSH commands
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        passphrase: ${{ secrets.EC2_PASSPHRASE }}
        script: |
          cd /path/to/your/deployment/directory
          git pull origin master
          docker-compose down
          docker-compose up -d --build
