name: Create File on EC2
on:
  push:
    branches:
      - master
 
jobs:
  create-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
 
    - name: Add EC2 to known hosts
      run: ssh-keyscan -H 54.164.30.247 >> ~/.ssh/known_hosts
 
    - name: Create a file on EC2
      run: |
        ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ec2-user@54.164.30.247 "echo 'Hello from GitHub Actions!' > /home/ec2-user/created_file.txt"
